#ifndef TOKENCODES_H
#define TOKENCODES_H

using namespace std;

enum TokenCodes
{
  ENDSYM, LPAREN, COLON, DECLARESYM, ELSESYM, ANDSYM, CHARACTERSYM, RPAREN,
  TIMES, GETSYM, PLUS, LEQ, MAINSYM, BITSYM, COMMA, LSS, EXPONENT, FLOATSYM,
  IFSYM, ORSYM, GEQ, CALLSYM, DIVIDE, EQL, MINUS, RETURNSSYM, WHILESYM, PUTSYM,
  NEQ, SEMICOLON, PROCEDURESYM, NOTSYM, DOSYM, GTR, TOSYM, FIXEDSYM, THENSYM,
  BYSYM, DATASYM, IDENT, INTEGERLIT, REALLIT, EOI, NAL
};

#endif
